name: Availability

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: ["", -alpine, -centos, -debian]
        flavor: ["", -jre, -jre-headless ]
        version:
          - 18.0.2
          - 18.0.1
          - 17.0.4
          - 17.0.3
          - 15.0.8
          - 15.0.7
          - 13.0.12
          - 13.0.11
          - 11.0.16
          - 11.0.15
          - 8u342
          - 8u332
          - 7u352
          - 6u119

        exclude:
          - version: 7u352
            flavor: -jre
          - version: 7u352
            flavor: -jre-headless
          - version: 6u119 
            flavor: -jre
          - version: 6u119 
            flavor: -jre-headless
    steps:
      - run: docker run --rm
          azul/zulu-openjdk${{matrix.distro}}:${{matrix.version}}${{matrix.flavor}}
          java -version
