name: Latest

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  repository_dispatch:
    types:
      - webhook

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: ["", -alpine, -centos, -debian]
        flavor: ["", -jre, -jre-headless ]
        version: [ 6, 7, 8, 11, 13, 15, 17, 18, 19, 20 ]
        latest_tag: [ "" ] # FIXME: by README it could be only "-latest"

        exclude:
          - version: 7
            flavor: -jre
          - version: 7
            flavor: -jre-headless
          - version: 6
            flavor: -jre
          - version: 6
            flavor: -jre-headless

    steps:
      - uses: actions/checkout@v3
      - run: ./test.sh test_latest ${{matrix.version}} "${{matrix.distro}}" "${{matrix.flavor}}${{matrix.latest_tag}}"
